In [180]:
import numpy as np

In [2]:
np.__version__

'1.21.4'

In [5]:
my_list=[4,8,15,16,23,42]

In [6]:
my_array_from_list=np.array(my_list)

In [7]:
my_array_from_list

array([ 4,  8, 15, 16, 23, 42])

In [8]:
my_array_from_list*10

array([ 40,  80, 150, 160, 230, 420])

In [9]:
my_tuple=(14,-3.57,5+7j)

In [10]:
np.array(my_tuple)

array([14.  +0.j, -3.57+0.j,  5.  +7.j])

In [11]:
np.array(my_tuple)*5

array([ 70.   +0.j, -17.85 +0.j,  25.  +35.j])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
len(np.arange(10,21))

11

In [15]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [16]:
np.linspace(0,30,11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [17]:
np.linspace(0,30,11).size

11

In [18]:
my_linspace=np.linspace(0,30,11,retstep=True)

In [19]:
my_linspace

(array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]), 3.0)

In [20]:
my_linspace[1]

3.0

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros((10,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0.,

In [27]:
np.zeros(11,dtype='str')

array(['', '', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [28]:
np.zeros(11,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [29]:
ave_vector=np.array([4,8,15,16,23,42])

In [30]:
ave_vector

array([ 4,  8, 15, 16, 23, 42])

In [31]:
ave_vector[1]

8

In [32]:
ave_vector[-1]

42

In [33]:
ave_vector[-3]

16

In [34]:
ave_vector[1]=14

In [35]:
ave_vector

array([ 4, 14, 15, 16, 23, 42])

In [36]:
ave_array=np.arange(35)

In [37]:
ave_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [38]:
ave_array.shape=(7,5)

In [39]:
ave_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [40]:
ave_array[1]

array([5, 6, 7, 8, 9])

In [41]:
ave_array[-1]

array([30, 31, 32, 33, 34])

In [42]:
ave_array[5,2]#row,column

27

In [43]:
row=5
column=2
ave_array[row,column]

27

In [44]:
ave_3D_array=np.arange(70)

In [45]:
ave_3D_array.shape=(2,7,5)

In [46]:
ave_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [47]:
5*ave_3D_array-10

array([[[-10,  -5,   0,   5,  10],
        [ 15,  20,  25,  30,  35],
        [ 40,  45,  50,  55,  60],
        [ 65,  70,  75,  80,  85],
        [ 90,  95, 100, 105, 110],
        [115, 120, 125, 130, 135],
        [140, 145, 150, 155, 160]],

       [[165, 170, 175, 180, 185],
        [190, 195, 200, 205, 210],
        [215, 220, 225, 230, 235],
        [240, 245, 250, 255, 260],
        [265, 270, 275, 280, 285],
        [290, 295, 300, 305, 310],
        [315, 320, 325, 330, 335]]])

In [48]:
left_math=np.arange(6).reshape((2,3))
right_math=np.arange(15).reshape((3,5))

In [49]:
dot_product=np.dot(left_math,right_math)

In [50]:
left_math

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
right_math

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
dot_product

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [53]:
ave_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [55]:
ave_3D_array.shape

(2, 7, 5)

In [56]:
ave_3D_array.sum()

2415

In [57]:
ave_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [58]:
ave_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [59]:
ave_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [60]:
ave_2D_array=np.ones(35,dtype='int_').reshape((7,5))*5

In [61]:
ave_2D_array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [62]:
ave_random_2D_array=np.random.random((7,5))

In [63]:
np.set_printoptions(precision=4)
ave_3D_array*ave_random_2D_array

array([[[ 0.    ,  0.5656,  1.2542,  0.3339,  1.9925],
        [ 2.4548,  1.155 ,  4.5701,  7.6328,  7.8212],
        [ 4.4129,  3.9962,  1.6258,  5.2677,  5.2623],
        [ 4.6713,  2.1626, 12.9212, 11.3309,  0.3629],
        [ 1.9358,  5.5107,  2.2441, 20.2225,  2.9281],
        [14.1924, 25.0493, 21.0792, 20.9457, 10.2662],
        [18.6013, 10.5083, 19.926 , 13.1367, 30.6838]],

       [[29.385 , 20.3623, 23.2035,  4.2299, 19.4273],
        [19.638 ,  7.8923, 27.4205, 41.0265, 38.2371],
        [19.8579, 16.7116,  6.3678, 19.45  , 18.4179],
        [15.5711,  6.8932, 39.5238, 33.3632,  1.0313],
        [ 5.3235, 14.6952,  5.8143, 50.9959,  7.1981],
        [34.0616, 58.7695, 48.4042, 47.1279, 22.6564],
        [40.3027, 22.3724, 41.72  , 27.0696, 62.2701]]])

In [64]:
ave_vector=np.arange(5)*7

In [65]:
ave_vector[0]=-1

In [66]:
ave_vector

array([-1,  7, 14, 21, 28])

In [67]:
ave_3D_array/ave_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [68]:
employee_data_def=[('name','S6'),('height','f8'),('weight','f8'),('age','i8')]

In [69]:
employee_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [74]:
employees_array = np.zeros((4),dtype=employee_data_def)


In [75]:
employees_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [76]:
employees_array[3]=('Donatello',200,100,105)

In [77]:
employees_array[0]=('Raphael',198,96,106)

In [78]:
employees_array

array([(b'Raphae', 198.,  96., 106), (b'',   0.,   0.,   0),
       (b'',   0.,   0.,   0), (b'Donate', 200., 100., 105)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [79]:
employees_array[0:]

array([(b'Raphae', 198.,  96., 106), (b'',   0.,   0.,   0),
       (b'',   0.,   0.,   0), (b'Donate', 200., 100., 105)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [80]:
employees_array[1:]

array([(b'',   0.,   0.,   0), (b'',   0.,   0.,   0),
       (b'Donate', 200., 100., 105)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [81]:
ages=employees_array['age']

In [82]:
ages

array([106,   0,   0, 105], dtype=int64)

In [84]:
company_employees_all=np.zeros((4,3,2), dtype=employee_data_def)

In [85]:
company_employees_all

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [86]:
company_employees_all[3,2,1]=('Pipin', 90, 120, 98)

In [87]:
company_employees_all

array([[[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'Pipin', 90., 120., 98)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [88]:
company_employees_all['height']

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0., 90.]]])

In [90]:
company_employees_all[['height','weight']]

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (90., 120.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

In [91]:
ave_array=(np.arange(24)).reshape(2,3,4)

In [92]:
ave_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [93]:
trial_ave_array=np.append(ave_array, [5,6,7,8])

In [94]:
trial_ave_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [95]:
trial_ave_array.reshape((7,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [96]:
new_trial_array=np.array(np.arange(24)).reshape(2,3,4)*10+5

In [97]:
new_trial_array

array([[[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [99]:
np.append(ave_array,new_trial_array,axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [101]:
np.append(ave_array,new_trial_array,axis=0).shape

(4, 3, 4)

In [100]:
np.append(ave_array,new_trial_array,axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [102]:
np.append(ave_array,new_trial_array,axis=1).shape

(2, 6, 4)

In [103]:
ave_stack=np.hstack((ave_array,new_trial_array))

In [104]:
ave_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [105]:
ave_stack=np.vstack((ave_array,new_trial_array))

In [106]:
ave_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [107]:
ave_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [108]:
insert_ave_array=np.insert(ave_array,1,666,axis=0)

In [109]:
insert_ave_array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[666, 666, 666, 666],
        [666, 666, 666, 666],
        [666, 666, 666, 666]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [110]:
insert_ave_array=np.insert(ave_array,1,666,axis=1)

In [111]:
insert_ave_array

array([[[  0,   1,   2,   3],
        [666, 666, 666, 666],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [666, 666, 666, 666],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [112]:
insert_ave_array=np.insert(ave_array,1,666,axis=2)

In [113]:
insert_ave_array

array([[[  0, 666,   1,   2,   3],
        [  4, 666,   5,   6,   7],
        [  8, 666,   9,  10,  11]],

       [[ 12, 666,  13,  14,  15],
        [ 16, 666,  17,  18,  19],
        [ 20, 666,  21,  22,  23]]])

In [114]:
del_array=np.empty(ave_array.shape)

In [115]:
np.copyto(del_array,ave_array)

In [116]:
del_array

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [117]:
np.delete(del_array,1,axis=0)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]])

In [118]:
np.delete(del_array,0,axis=0)

array([[[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [119]:
np.delete(del_array,1,axis=1)

array([[[ 0.,  1.,  2.,  3.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [20., 21., 22., 23.]]])

In [120]:
np.delete(del_array,1,axis=2)

array([[[ 0.,  2.,  3.],
        [ 4.,  6.,  7.],
        [ 8., 10., 11.]],

       [[12., 14., 15.],
        [16., 18., 19.],
        [20., 22., 23.]]])

In [121]:
alpha=np.array([[1,2],[3,4]])
beta=np.array([[5,6]])


In [122]:
alpha

array([[1, 2],
       [3, 4]])

In [176]:
beta

array([[5, 6]])

In [125]:
together=np.concatenate((alpha,beta),axis=0)

In [126]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
together.shape

(3, 2)

In [128]:
together[1,1]=666

In [130]:
together

array([[  1,   2],
       [  3, 666],
       [  5,   6]])

In [132]:
arrays=np.zeros((5,3,4))
for n in range(5):
    arrays[n]=np.random.randn(3,4)
arrays    

array([[[-0.385 ,  0.5096,  0.4038, -0.5357],
        [ 0.4268, -0.2636,  1.0685, -0.5677],
        [-0.5218,  0.1724,  0.3325, -0.869 ]],

       [[-0.1104, -0.6816,  0.1935,  0.3189],
        [-1.3978,  0.355 ,  0.1039,  0.3192],
        [ 0.2116, -0.2139,  0.088 , -0.9849]],

       [[-0.1172,  1.2074, -2.2486,  1.019 ],
        [ 0.7463, -0.363 ,  0.4369, -0.1412],
        [-1.1639, -0.2832, -0.9041,  1.0924]],

       [[-0.0156,  0.1888, -0.634 , -0.601 ],
        [-0.6835,  0.0655, -0.7067, -1.7648],
        [-1.2232,  2.4612,  0.7695,  0.4906]],

       [[ 2.9312, -1.0088,  1.6063, -0.4691],
        [-1.7289, -0.2698,  0.1064, -0.5068],
        [ 0.4028,  2.1152,  0.9622, -0.0221]]])

In [133]:
stack0=np.stack(arrays,axis=0)
stack1=np.stack(arrays,axis=1)
stack2=np.stack(arrays,axis=2)

In [134]:
stack0

array([[[-0.385 ,  0.5096,  0.4038, -0.5357],
        [ 0.4268, -0.2636,  1.0685, -0.5677],
        [-0.5218,  0.1724,  0.3325, -0.869 ]],

       [[-0.1104, -0.6816,  0.1935,  0.3189],
        [-1.3978,  0.355 ,  0.1039,  0.3192],
        [ 0.2116, -0.2139,  0.088 , -0.9849]],

       [[-0.1172,  1.2074, -2.2486,  1.019 ],
        [ 0.7463, -0.363 ,  0.4369, -0.1412],
        [-1.1639, -0.2832, -0.9041,  1.0924]],

       [[-0.0156,  0.1888, -0.634 , -0.601 ],
        [-0.6835,  0.0655, -0.7067, -1.7648],
        [-1.2232,  2.4612,  0.7695,  0.4906]],

       [[ 2.9312, -1.0088,  1.6063, -0.4691],
        [-1.7289, -0.2698,  0.1064, -0.5068],
        [ 0.4028,  2.1152,  0.9622, -0.0221]]])

In [135]:
stack1

array([[[-0.385 ,  0.5096,  0.4038, -0.5357],
        [-0.1104, -0.6816,  0.1935,  0.3189],
        [-0.1172,  1.2074, -2.2486,  1.019 ],
        [-0.0156,  0.1888, -0.634 , -0.601 ],
        [ 2.9312, -1.0088,  1.6063, -0.4691]],

       [[ 0.4268, -0.2636,  1.0685, -0.5677],
        [-1.3978,  0.355 ,  0.1039,  0.3192],
        [ 0.7463, -0.363 ,  0.4369, -0.1412],
        [-0.6835,  0.0655, -0.7067, -1.7648],
        [-1.7289, -0.2698,  0.1064, -0.5068]],

       [[-0.5218,  0.1724,  0.3325, -0.869 ],
        [ 0.2116, -0.2139,  0.088 , -0.9849],
        [-1.1639, -0.2832, -0.9041,  1.0924],
        [-1.2232,  2.4612,  0.7695,  0.4906],
        [ 0.4028,  2.1152,  0.9622, -0.0221]]])

In [136]:
stack2

array([[[-0.385 , -0.1104, -0.1172, -0.0156,  2.9312],
        [ 0.5096, -0.6816,  1.2074,  0.1888, -1.0088],
        [ 0.4038,  0.1935, -2.2486, -0.634 ,  1.6063],
        [-0.5357,  0.3189,  1.019 , -0.601 , -0.4691]],

       [[ 0.4268, -1.3978,  0.7463, -0.6835, -1.7289],
        [-0.2636,  0.355 , -0.363 ,  0.0655, -0.2698],
        [ 1.0685,  0.1039,  0.4369, -0.7067,  0.1064],
        [-0.5677,  0.3192, -0.1412, -1.7648, -0.5068]],

       [[-0.5218,  0.2116, -1.1639, -1.2232,  0.4028],
        [ 0.1724, -0.2139, -0.2832,  2.4612,  2.1152],
        [ 0.3325,  0.088 , -0.9041,  0.7695,  0.9622],
        [-0.869 , -0.9849,  1.0924,  0.4906, -0.0221]]])

In [137]:
before_split=stack0

In [138]:
before_split.shape

(5, 3, 4)

In [139]:
s0=np.split(before_split,5,axis=0)

In [140]:
s0

[array([[[-0.385 ,  0.5096,  0.4038, -0.5357],
         [ 0.4268, -0.2636,  1.0685, -0.5677],
         [-0.5218,  0.1724,  0.3325, -0.869 ]]]),
 array([[[-0.1104, -0.6816,  0.1935,  0.3189],
         [-1.3978,  0.355 ,  0.1039,  0.3192],
         [ 0.2116, -0.2139,  0.088 , -0.9849]]]),
 array([[[-0.1172,  1.2074, -2.2486,  1.019 ],
         [ 0.7463, -0.363 ,  0.4369, -0.1412],
         [-1.1639, -0.2832, -0.9041,  1.0924]]]),
 array([[[-0.0156,  0.1888, -0.634 , -0.601 ],
         [-0.6835,  0.0655, -0.7067, -1.7648],
         [-1.2232,  2.4612,  0.7695,  0.4906]]]),
 array([[[ 2.9312, -1.0088,  1.6063, -0.4691],
         [-1.7289, -0.2698,  0.1064, -0.5068],
         [ 0.4028,  2.1152,  0.9622, -0.0221]]])]

In [141]:
s1=np.split(before_split,3,axis=1)

In [142]:
s1

[array([[[-0.385 ,  0.5096,  0.4038, -0.5357]],
 
        [[-0.1104, -0.6816,  0.1935,  0.3189]],
 
        [[-0.1172,  1.2074, -2.2486,  1.019 ]],
 
        [[-0.0156,  0.1888, -0.634 , -0.601 ]],
 
        [[ 2.9312, -1.0088,  1.6063, -0.4691]]]),
 array([[[ 0.4268, -0.2636,  1.0685, -0.5677]],
 
        [[-1.3978,  0.355 ,  0.1039,  0.3192]],
 
        [[ 0.7463, -0.363 ,  0.4369, -0.1412]],
 
        [[-0.6835,  0.0655, -0.7067, -1.7648]],
 
        [[-1.7289, -0.2698,  0.1064, -0.5068]]]),
 array([[[-0.5218,  0.1724,  0.3325, -0.869 ]],
 
        [[ 0.2116, -0.2139,  0.088 , -0.9849]],
 
        [[-1.1639, -0.2832, -0.9041,  1.0924]],
 
        [[-1.2232,  2.4612,  0.7695,  0.4906]],
 
        [[ 0.4028,  2.1152,  0.9622, -0.0221]]])]

In [143]:
ave_start_array=np.array(np.arange(24))

In [144]:
ave_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [145]:
ave_start_array.shape

(24,)

In [146]:
ave_3_8_array=ave_start_array.reshape((3,8))

In [147]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [149]:
for n in ave_3_8_array.flat:
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [150]:
ave_start_array=np.array(np.arange(24))
ave_3_8_array=ave_start_array.reshape((3,8))
ave_2_3_4_array=ave_3_8_array.reshape((2,3,4))

In [151]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [153]:
flipper=np.fliplr(ave_3_8_array)

In [154]:
flipper

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [155]:
ave_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [156]:
np.fliplr(ave_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [157]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [158]:
np.flipud(ave_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [159]:
np.flipud(ave_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [160]:
ave_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [161]:
np.roll(ave_start_array,5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [162]:
np.roll(ave_start_array,-5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [163]:
ave_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [164]:
np.roll(ave_2_3_4_array,2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [165]:
np.roll(ave_2_3_4_array,-2)

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23,  0,  1]]])

In [166]:
ave_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [167]:
np.rot90(ave_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [168]:
ave_array_one=np.array(np.arange(10))

In [169]:
ave_array_one

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
np.tile(ave_array_one,5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9])

In [171]:
np.tile(ave_array_one,5).reshape(5,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [172]:
ave_array_two=np.array(np.arange(7))

In [173]:
tile_1=np.tile(ave_array_two,(3,1))

In [174]:
tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [179]:
np.repeat(ave_array_two,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])